{% set version = "1.4" %}

package:
  name: py3c
  version: {{ version }}

source:
  url: https://github.com/encukou/py3c/archive/v{{ version }}.tar.gz
  sha256: abc745079ef906148817f4472c3fb4bc41d62a9ea51a746b53e09819494ac006

build:
  number: 1

requirements:
  build:
    - m2-base  # [win]
    - m2-sed  # [win]
    - m2-make  # [win]
    - m2-bash  # [win]
    - m2-coreutils  # [win]
    - make  # [unix]
  host:

test:
  commands:
    - test -f "${PREFIX}/include/py3c.h"           # [unix]
    - test -d "${PREFIX}/include/py3c"             # [unix]
    - if not exist "%LIBRARY_INC%\\py3c.h" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\py3c" exit 1    # [win]

about:
  home: https://github.com/encukou/py3c
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: A Python 2/3 compatibility layer for C extensions

  dev_url: https://github.com/encukou/py3c
  doc_url: https://py3c.readthedocs.org/

extra:
  recipe-maintainers:
    - jakirkham
