{% set version = "1.3.1" %}

package:
  name: py3c
  version: {{ version }}

source:
  url: https://github.com/encukou/py3c/archive/v{{ version }}.tar.gz
  sha256: f3e138623a87cde2cd7d8e98b51447e033d43a3f639c5054185c859fa1888727

build:
  number: 0

requirements:
  build:
    - posix  # [win]
  host:

test:
  commands:
    - test -f "${PREFIX}/include/py3c.h"           # [unix]
    - test -d "${PREFIX}/include/py3c"             # [unix]
    - if not exist "%LIBRARY_INC%\\py3c.h" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\py3c" exit 1    # [win]

about:
  home: https://github.com/encukou/py3c
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: A Python 2/3 compatibility layer for C extensions

  dev_url: https://github.com/encukou/py3c
  doc_url: https://py3c.readthedocs.org/

extra:
  recipe-maintainers:
    - jakirkham
